USE HRSystem_iplusplus;

DROP TABLE IF EXISTS Technical;

DROP TABLE IF EXISTS Projects;

DROP TABLE IF EXISTS Customer;

DROP TABLE IF EXISTS Sales;

DROP TABLE IF EXISTS BankDetails;

DROP TABLE IF EXISTS Employee;
